apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-16T15:52:11Z"
  labels:
    app: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: "{{ .Release.Name }}"
  namespace: default
  resourceVersion: "80896"
  uid: 736cd326-0096-4fe0-a753-e0e77b3632ee
spec:
  clusterIP: 
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31581
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ .Release.Name }}"
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
status:
  loadBalancer: {}
